name: Nightly Tests
on:
  schedule:
    - cron: '20 10 * * *' # run at 10:20 AM UTC
  workflow_dispatch:  # to trigger manually

permissions:
  contents: read

jobs:
  doctest:
    uses: ./.github/workflows/doctest.yaml
    secrets: inherit
  format:
    uses: ./.github/workflows/format.yaml
  pre-commit:
    uses: ./.github/workflows/pre-commit.yaml
  test:
    uses: ./.github/workflows/test.yaml
  test-deps:
    uses: ./.github/workflows/test-deps.yaml
